version: 2.1

deployment:
  production:
    branch: main
    commands:
      - surge --project ./build --domain jordan-asano-financialapp.surge.sh

jobs:
  build:
    executor: node-executor
    steps:
      - checkout

      # Cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run Tests
          command: npm test

      - run:
          name: Build Application
          command: npm run build

      - persist_to_workspace:
          root: .
          paths:
            - build

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build