version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14.17.0
    working_directory: ~/repo

jobs:
  build:
    executor: node-executor
    steps:
      - checkout

      # Cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build Application
          command: npm run build

      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install Surge
          command: sudo npm install -g surge
      - run:
          name: Deploy to Surge
          command: surge --project ./build --domain jordan-asano-financialapp.surge.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build